title:             CoLab
email:             nikos.agelides@yahoo.com
description:       CoLab front page
author:            Nicolas Angelides
baseurl:           ""
url:               "http://colab.earth/"

# Social Profiles
twitter_username:  regnidorhcs
github_username:   regnidorhcs
facebook_username: I.am.lost.in.a.rainbow

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
